### ISSUE TITLE
Radio 单选框选中时候圆点没有居中

### ISSUE THREAD

**Issue by Francis1024** [ecaps1038/yike-design-dev#10]
![image](https://github.com/ecaps1038/yike-design-dev/assets/34295704/003ce1d9-c2ab-4dc2-a491-c16bb82c9190)

**Comment by Francis1024** [comment]
#11

**Comment by ecaps1038** [comment]
感谢，重构中会修改调整，

**Comment by Rickon-DAFEI** [comment]
已重构
