### ISSUE TITLE
Dropdown组件样式不生效

### ISSUE THREAD

**Issue by Gung9527** [ecaps1038/yike-design-dev#219]
在开发分页组件时发现，如果直接加载当前页面，Dropdown的样式会不生效
![image](https://github.com/ecaps1038/yike-design-dev/assets/43003335/94f0d086-ce1f-498c-b82f-c8dce077371a)

当切换到其他组件的页面再切换回去分页组件页面后，样式又会生效
![image](https://github.com/ecaps1038/yike-design-dev/assets/43003335/b1c6a50e-92ed-4968-8bae-309c5e25bf97)

**Comment by Rickon-DAFEI** [comment]
看一下在分页组件中手动引入Dropdown的css文件能否解决该问题
