### ISSUE TITLE
手动输入超出界限值拦截失败。

### ISSUE THREAD

**Issue by zhounie** [ecaps1038/yike-design-dev#267]
![image](https://github.com/ecaps1038/yike-design-dev/assets/35126048/a10c0ab1-d065-4d56-a218-b3c1f600f4d5)

**Comment by zhounie** [comment]
![image](https://github.com/ecaps1038/yike-design-dev/assets/35126048/825d557d-acaa-4675-8989-7f96f14f5974)
watch没有对第二次update做出反应(两次都是重复值)。

**Comment by fgt1t5y** [comment]
这个貌似修复了
