### ISSUE TITLE
TreeSelect树形选择的时候 在点击图片里面的叉叉会报错

### ISSUE THREAD

**Issue by YY-x** [ecaps1038/yike-design-dev#289]
TreeSelect树形选择的时候 在点击图片里面的叉叉会报错

<img width="1666" alt="image" src="https://github.com/ecaps1038/yike-design-dev/assets/66400381/e62c43c9-9a77-4538-869d-85cedeb7f5cb">

**Comment by Zzongke** [comment]
![image](https://github.com/ecaps1038/yike-design-dev/assets/65376724/ff020e28-710a-4641-999e-29c42f6b8df9)

- inputValue.value为空了，下面findByLabel里面的数组label除非为`""`,否则不可能找到里面有值的，所以导致出错，所以这里事件直接返回空？

**Comment by fgt1t5y** [comment]
> ![image](https://user-images.githubusercontent.com/65376724/270586561-ff020e28-710a-4641-999e-29c42f6b8df9.png)
> 
>     * inputValue.value为空了，下面findByLabel里面的数组label除非为`""`,否则不可能找到里面有值的，所以导致出错，所以这里事件直接返回空？ @fgt1t5y

抱歉才看到 确实应该返回空
