### ISSUE TITLE
YkInputTag 标签输入框 提示报错

### ISSUE THREAD

**Issue by YY-x** [ecaps1038/yike-design-dev#291]
YkInputTag 标签输入框 提示报错
<img width="1620" alt="image" src="https://github.com/ecaps1038/yike-design-dev/assets/66400381/10aacc79-895f-47d4-8a82-5fdb52ee6747">

**Comment by fgt1t5y** [comment]
已修复~ 请拉最新的源码看看。

**Comment by YY-x** [comment]
[666]
