### ISSUE TITLE
Calendar 日历组件 高亮显示错误

### ISSUE THREAD

**Issue by YY-x** [ecaps1038/yike-design-dev#295]
Calendar 日历组件 高亮显示错误，比如图片中为什么29号亮了 30、31没亮，下面3号亮了1、2号没亮
<img width="1641" alt="image" src="https://github.com/ecaps1038/yike-design-dev/assets/66400381/53733eaf-4086-4b70-86c2-7619ddaa9ac1">

**Comment by fgt1t5y** [comment]
已解决
