### ISSUE TITLE
关于Drawer组件使用产生的一个细节BUG!

### ISSUE THREAD

**Issue by sunjianfengHub** [ecaps1038/yike-design-dev#313]
你好，首先我无法为你提供直接的证据证明这个问题。当你在使用Drawer的时候由于overflow的原因导致滚动条的消失，那样就会造成整个页面元素横行的偏移闪烁！

**Comment by fgt1t5y** [comment]
我是Drawer的开发者 这个我也没有什么好办法解决

这几天我研究一下吧。你有好的解决思路欢迎告诉我~~

**Comment by fgt1t5y** [comment]
弄好了 请拉最新代码再尝试看看。这个仓库Github Action 构建好像出问题了，只能拉代码看了。
