### ISSUE TITLE
点击某个锚点后 界面刷新 刷新后页面没内容

### ISSUE THREAD

**Issue by YY-x** [ecaps1038/yike-design-dev#314]
<img width="1671" alt="image" src="https://github.com/ecaps1038/yike-design-dev/assets/66400381/2d1e791b-7263-4f71-a050-12e9312f03ac">

点击刷新后 内容都是空
![Uploading image.png…]()

**Comment by YY-x** [comment]
<img width="1667" alt="image" src="https://github.com/ecaps1038/yike-design-dev/assets/66400381/42d16860-9a2e-49b4-aa15-6eba1aa51b7c">

**Comment by fgt1t5y** [comment]
这是因为文档现在的路由模式是hash模式造成的。之前文档的路由模式是history模式，不会有这个问题，但后面部署到Github Pages后访问非首页会报404，于是乎换成了hash模式，后面再解决吧
