### ISSUE TITLE
table组件功能缺陷

### ISSUE THREAD

**Issue by ecaps1038** [ecaps1038/yike-design-dev#341]
table组件我们不必很复杂，但是现在似乎只能展示数据，目前功能缺少单行控制能力，比如点击删除某一行数据事件的插入~
<img width="1566" alt="image" src="https://github.com/ecaps1038/yike-design-dev/assets/16243132/245ae18f-febc-4b73-af31-7b8c18d65428">
比如要要对现在的这两个按钮插入对应行的真实事件该如何操作？

**Comment by Rickon-DAFEI** [comment]
该组件封装有插槽透传数据行信息如下
![image](https://github.com/ecaps1038/yike-design-dev/assets/51977404/c1bcf6b1-d6a1-4be0-bcf1-0da4470c22fe)
使用案例如下：
```
<yk-table :data="dataList" @selection-change="handleSelectionChange">
    <yk-table-column property="name" label="用户名"></yk-table-column>
    <yk-table-column property="email" label="邮箱"></yk-table-column>
    <yk-table-column property="bir" label="生日"></yk-table-column>
    <yk-table-column property="desc" label="操作">
      <template #default="row">
        <yk-button type="secondary" status="primary" @click="handleAdd(row)">
          添加
        </yk-button>
        <yk-button
          type="outline"
          status="primary"
          style="margin-left: 8px"
          @click="handleDelete(row)"
        >
          删除
        </yk-button>
      </template>
    </yk-table-column>
  </yk-table>

const handleAdd = (e) => {
  console.log('🚀 Add ~ e:', e)
}
const handleDelete = (e) => {
  console.log('🚀 Delete ~ e:', e)
}
```
当前版本实现issue中需要的能力可以尝试采用如下操作
1. dataList 数据源提供索引值，操作数据行后可以根据结构row中的结构的索引值信息直接在外部修改数据源
具体使用实例会在后续版本更新中给出

TODO
* 针对table组件的能力实现问题，目前考虑透传自动产生的数据行所在对应索引值以便用户进行数据修改操作
* 提供完整的数据行操作示例以及说明文档
