### ISSUE TITLE
关于 image 图片懒加载问题

### ISSUE THREAD

**Issue by ecaps1038** [ecaps1038/yike-design-dev#347]
我在代码中禁止了懒加载如下
<img width="964" alt="QQ20240330-091401@2x" src="https://github.com/ecaps1038/yike-design-dev/assets/16243132/7507a3c3-d34b-470c-a85b-e7470090c88a">
在第一页图片是不加载直接出现的 
<img width="1403" alt="image" src="https://github.com/ecaps1038/yike-design-dev/assets/16243132/fd90e32a-e3bb-4a44-a7f7-ce99a6c5afef">
但当到第二页就不会直接出现，一直处于加载状态
<img width="1390" alt="image" src="https://github.com/ecaps1038/yike-design-dev/assets/16243132/ae625d60-d059-406f-8431-ad9561dac5ae">

**Comment by ecaps1038** [comment]
我发现是由于懒加载方法，必须是在滚动后出入视觉窗口才会判断true或false，如果没有滚动根本不不会进行触发判断
<img width="819" alt="image" src="https://github.com/ecaps1038/yike-design-dev/assets/16243132/634385f1-095f-440b-a8a3-049cf8371491">

**Comment by Rickon-DAFEI** [comment]
提供一下分页及图片列表template部分及分页操作触发事件的代码
我这边尝试复现～

**Comment by ecaps1038** [comment]
//类似下面的使用

<template>
  <yk-space dir="vertical">
    <yk-image
      v-for="(item,index) in photosList"
      :key="index"
      :src="'src/assets/images/'+item"
      width="400"
      height="400"
      fit="cover"
      :is-lazy="false"
    ></yk-image>
  </yk-space>
  <yk-pagination :total="photos.length" size="m" :page-size="8" @change="changePage"></yk-pagination>
</template>
<script setup lang='ts'>
import { ref } from 'vue'
defineOptions({
  name: 'Test',
})
const nowPage = ref<number>(1)
const photosList = ref()
//图片合集
const photos = [
  'a.jpeg',
  'b.jpeg',
  'c.jpeg',
  'd.jpeg',
  'e.jpeg',
  'f.jpeg',
  'g.jpeg',
  'h.jpeg',
  'i.jpeg',
  'j.jpeg',
  'k.jpeg',
  'l.jpeg',
  'm.jpeg',
  'n.jpeg',
  'o.jpeg',
  'p.jpeg',
  'q.jpeg',
]

//获取数据
const drawPhotos = () => {
  let arr = photos.slice((nowPage.value - 1) * 6, nowPage.value * 8)
  photosList.value = arr
}
drawPhotos()
//切换页码
const changePage = (e: number) => {
  nowPage.value = e
  drawPhotos()
}
</script>
<style lang='less' scoped>
</style>

**Comment by ecaps1038** [comment]
`<template>
  <yk-space dir="vertical">
    <yk-image
      v-for="(item,index) in photosList"
      :key="index"
      :src="'src/assets/images/'+item"
      width="400"
      height="400"
      fit="cover"
      :is-lazy="false"
    ></yk-image>
  </yk-space>
  <yk-pagination :total="photos.length" size="m" :page-size="8" @change="changePage"></yk-pagination>
</template>
<script setup lang='ts'>
import { ref } from 'vue'
defineOptions({
  name: 'Test',
})
const nowPage = ref<number>(1)
const photosList = ref()
//图片合集
const photos = [
  'a.jpeg',
  'b.jpeg',
  'c.jpeg',
  'd.jpeg',
  'e.jpeg',
  'f.jpeg',
  'g.jpeg',
  'h.jpeg',
  'i.jpeg',
  'j.jpeg',
  'k.jpeg',
  'l.jpeg',
  'm.jpeg',
  'n.jpeg',
  'o.jpeg',
  'p.jpeg',
  'q.jpeg',
]

//获取数据
const drawPhotos = () => {
  let arr = photos.slice((nowPage.value - 1) * 6, nowPage.value * 8)
  photosList.value = arr
}
drawPhotos()
//切换页码
const changePage = (e: number) => {
  nowPage.value = e
  drawPhotos()
}
</script>
<style lang='less' scoped>
</style>`

**Comment by ecaps1038** [comment]
[test.vue.zip](https://github.com/ecaps1038/yike-design-dev/files/14821003/test.vue.zip)
如上述的例子，图片是本地的

**Comment by Rickon-DAFEI** [comment]
```
    <template v-for="item in photosList" :key="item">
      <yk-image
        :src="item"
        width="400"
        height="400"
        fit="cover"
        :is-lazy="true"
      ></yk-image>
    </template>
```
判断是在更改yk-image中的src时，所在dom不会走mounted生命周期，只有滚动才会重新触发自定义指令
上述代码是保证分页时先消毁image再重新加载

如果需要正常触发，可能需要用其他事件监听方法替代自定义指令实现滚动检测是否可见
