### ISSUE TITLE
Pagination 分页 Bug

### ISSUE THREAD

**Issue by gscsds** [ecaps1038/yike-design-dev#53]
![bug](https://github.com/ecaps1038/yike-design-dev/assets/40168832/6246730d-3231-4158-9577-874f9212c0e4)

**Comment by baizuige** [comment]
bug是这么报的吗。。。

**Comment by ecaps1038** [comment]
该组件会进行重构，不知道目前是发现有什么样的bug

**Comment by gscsds** [comment]
应该不算BUG 我看了下就是show判断的时候少了条件
